projects:
- id: proj_669ee54932ec
  name: test_proj
  root_path: /Users/xiaocanguo/Github/lex_mint/test_proj
  description: null
  created_at: '2026-02-10T12:59:40.507534'
  updated_at: '2026-02-10T12:59:40.507580'
