projects:
- id: proj_010d3943001e
  name: gamedesign2test
  root_path: C:\Users\qaz\Documents\gamedesign2test
  description: null
  created_at: '2026-02-01T14:37:27.277393'
  updated_at: '2026-02-01T14:37:31.489172'
- id: proj_050cda65a0f8
  name: test4
  root_path: C:\Users\qaz\Documents\gamedesign2test3
  description: null
  created_at: '2026-02-01T15:27:22.526398'
  updated_at: '2026-02-02T01:36:37.192917'
