chunking:
  chunk_overlap: 200
  chunk_size: 1000
embedding:
  api_base_url: https://api.jina.ai/v1
  api_key: jina_17b1807b9d724d238dd5165a6d891b50BW0BrQZpr1rRdSccoIHUG5OuHZay
  api_model: jina-embeddings-v3
  local_device: cpu
  local_model: all-MiniLM-L6-v2
  provider: api
retrieval:
  score_threshold: 0.1
  top_k: 5
storage:
  persist_directory: data/chromadb
